# Generated by Django 5.0.1 on 2024-01-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identification', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=6)),
                ('color', models.CharField(max_length=50)),
                ('infractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infractions.person')),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infractions.officer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infractions.vehicle')),
            ],
        ),
    ]
