# Generated by Django 5.0.1 on 2024-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infractions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraction',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
