# Generated by Django 5.0.1 on 2024-01-20 16:21

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    CustomUser = apps.get_model("utilities", "CustomUser")
    superuser = CustomUser(
        username="admin",
        password=make_password("Hola123..."),
        is_staff=True,
        is_superuser=True,
    )
    superuser.save()


class Migration(migrations.Migration):
    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
