# Generated by Django 4.2.4 on 2023-09-13 00:31

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    CustomUser = apps.get_model('utilities', 'CustomUser')
    superuser = CustomUser(
        username='admin',
        password=make_password('Hola123...'),
        is_staff=True,
        is_superuser=True,
    )
    superuser.save()



class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
